version: "3"

services:
  arkeo-node:
    image: ghcr.io/arkeonetwork/arkeo-testnet:latest
    entrypoint:
      - /usr/bin/uramd
    command:
      - start
      - --pruning
      - nothing
      - --minimum-gas-prices
      - 0.0001uuram
      - --home 
      - /root/.uram
    ports:
      - 1317:1317
      - 26657:26657
      - 26656:26656
    volumes:
      - ./uram-data:/root/.uram/:z
      - /tmp:/tmp:z