// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: uram/uram/v1/scooter.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Scooter defines the Scooter message.
type Scooter struct {
	Id       uint64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Location string      `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Active   bool        `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Owner    string      `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Creator  string      `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Price    *types.Coin `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
}

func (m *Scooter) Reset()         { *m = Scooter{} }
func (m *Scooter) String() string { return proto.CompactTextString(m) }
func (*Scooter) ProtoMessage()    {}
func (*Scooter) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1d9215b44c5c0f3, []int{0}
}
func (m *Scooter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Scooter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Scooter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Scooter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scooter.Merge(m, src)
}
func (m *Scooter) XXX_Size() int {
	return m.Size()
}
func (m *Scooter) XXX_DiscardUnknown() {
	xxx_messageInfo_Scooter.DiscardUnknown(m)
}

var xxx_messageInfo_Scooter proto.InternalMessageInfo

func (m *Scooter) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Scooter) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Scooter) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Scooter) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Scooter) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Scooter) GetPrice() *types.Coin {
	if m != nil {
		return m.Price
	}
	return nil
}

func init() {
	proto.RegisterType((*Scooter)(nil), "uram.uram.v1.Scooter")
}

func init() { proto.RegisterFile("uram/uram/v1/scooter.proto", fileDescriptor_a1d9215b44c5c0f3) }

var fileDescriptor_a1d9215b44c5c0f3 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0x41, 0x4a, 0xc4, 0x30,
	0x18, 0x85, 0xe7, 0xaf, 0xd3, 0xce, 0x18, 0x45, 0x30, 0x88, 0xc4, 0x2e, 0x42, 0x71, 0x55, 0x10,
	0x12, 0xaa, 0x37, 0xd0, 0x1b, 0xd4, 0x9d, 0xbb, 0x34, 0x93, 0x45, 0xc0, 0xe9, 0x5f, 0x92, 0x58,
	0xf5, 0x16, 0x9e, 0xc4, 0x73, 0xb8, 0x9c, 0xa5, 0x4b, 0x69, 0x2f, 0x22, 0x93, 0x8c, 0x6e, 0x7e,
	0xf8, 0x1e, 0xef, 0xc1, 0xfb, 0x1f, 0x29, 0x5f, 0x9c, 0xda, 0xca, 0x78, 0xc6, 0x46, 0x7a, 0x8d,
	0x18, 0x8c, 0x13, 0x83, 0xc3, 0x80, 0xf4, 0x74, 0x2f, 0x8b, 0x78, 0xc6, 0xa6, 0xe4, 0x1a, 0xfd,
	0x16, 0xbd, 0xec, 0x94, 0x37, 0x72, 0x6c, 0x3a, 0x13, 0x54, 0x23, 0x35, 0xda, 0x3e, 0xb9, 0xaf,
	0x3f, 0x81, 0xac, 0x1e, 0x53, 0x9e, 0x9e, 0x91, 0xcc, 0x6e, 0x18, 0x54, 0x50, 0x2f, 0xdb, 0xcc,
	0x6e, 0x68, 0x49, 0xd6, 0xcf, 0xa8, 0x55, 0xb0, 0xd8, 0xb3, 0xac, 0x82, 0xfa, 0xb8, 0xfd, 0x67,
	0x7a, 0x49, 0x0a, 0xa5, 0x83, 0x1d, 0x0d, 0x3b, 0xaa, 0xa0, 0x5e, 0xb7, 0x07, 0xa2, 0x17, 0x24,
	0xc7, 0xd7, 0xde, 0x38, 0xb6, 0x8c, 0x81, 0x04, 0x94, 0x91, 0x95, 0x76, 0x46, 0x05, 0x74, 0x2c,
	0x8f, 0xfa, 0x1f, 0x52, 0x49, 0xf2, 0xc1, 0x59, 0x6d, 0x58, 0x51, 0x41, 0x7d, 0x72, 0x7b, 0x25,
	0x52, 0x5f, 0xb1, 0xef, 0x2b, 0x0e, 0x7d, 0xc5, 0x03, 0xda, 0xbe, 0x4d, 0xbe, 0xfb, 0x9b, 0xaf,
	0x89, 0xc3, 0x6e, 0xe2, 0xf0, 0x33, 0x71, 0xf8, 0x98, 0xf9, 0x62, 0x37, 0xf3, 0xc5, 0xf7, 0xcc,
	0x17, 0x4f, 0xe7, 0x71, 0x8f, 0xb7, 0x34, 0x4b, 0x78, 0x1f, 0x8c, 0xef, 0x8a, 0xf8, 0xe4, 0xdd,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x91, 0xf9, 0xf1, 0xbc, 0x30, 0x01, 0x00, 0x00,
}

func (m *Scooter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Scooter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Scooter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Price != nil {
		{
			size, err := m.Price.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintScooter(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintScooter(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintScooter(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x22
	}
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Location) > 0 {
		i -= len(m.Location)
		copy(dAtA[i:], m.Location)
		i = encodeVarintScooter(dAtA, i, uint64(len(m.Location)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintScooter(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintScooter(dAtA []byte, offset int, v uint64) int {
	offset -= sovScooter(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Scooter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovScooter(uint64(m.Id))
	}
	l = len(m.Location)
	if l > 0 {
		n += 1 + l + sovScooter(uint64(l))
	}
	if m.Active {
		n += 2
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovScooter(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovScooter(uint64(l))
	}
	if m.Price != nil {
		l = m.Price.Size()
		n += 1 + l + sovScooter(uint64(l))
	}
	return n
}

func sovScooter(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozScooter(x uint64) (n int) {
	return sovScooter(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Scooter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowScooter
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Scooter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Scooter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowScooter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowScooter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthScooter
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthScooter
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Location = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowScooter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowScooter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthScooter
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthScooter
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowScooter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthScooter
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthScooter
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowScooter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthScooter
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthScooter
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Price == nil {
				m.Price = &types.Coin{}
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipScooter(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthScooter
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipScooter(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowScooter
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowScooter
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowScooter
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthScooter
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupScooter
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthScooter
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthScooter        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowScooter          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupScooter = fmt.Errorf("proto: unexpected end of group")
)
