apiVersion: v1
kind: Service
metadata:
  name: uramd-service
  namespace: foundation
  labels:
    app: uramd
spec:
  type: LoadBalancer
  ports:
    - port: 26656
      name: p2p
    - port: 26657
      name: rpc
    - port: 1317
      name: lcd
  selector:
    app: uramd
